# docker-compose.yaml
version: '3.8'
services:
  jenkins-agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    container_name: jenkins-agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa 