version: '3'
 
services:
 elasticsearch:
   image: elasticsearch:8.6.2
   environment:
     - cluster.name=el-cluster
     - discovery.type=single-node
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - xpack.security.enabled=false
   ulimits:
     memlock:
       soft: -1
       hard: -1
   ports:
     - "9200:9200"
 kibana:
   image: kibana:8.6.2
   ports:
     - "5601:5601"