apiVersion: v1
kind: Service
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  type: NodePort
  selector:
    app: go-server
  ports:
    - name: go-server
      port: 8081
      targetPort: 8081
      nodePort: 30000
